### ISSUE TITLE
Debugger not hitted back on  line mentioned

### ISSUE THREAD

**Issue by timriley1234** [checkout/checkout-sdk-net#164]
### Environment

* Checkout SDK version: 3.5.1
* Platform and version: VS 2019
* Operating System and version: Windows 10

### Description

Dim resp As HostedPaymentResponse = api.HostedPaymentsClient().Create(requestRRR).Result ---  This line it keeps on rotating and it not hits back any response after passing the HostedPaymentRequest. 

Code reference:
Imports Checkout
Imports Checkout.Common
Imports Checkout.Payments
Imports Checkout.Payments.Hosted

Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        Dim api As ICheckoutApi = CheckoutSdk.DefaultSdk().StaticKeys().PublicKey("pk_test_9759a4b3-c988-49f7-961e-434c309d843d").SecretKey("sk_test_680cafb5-baf2-4d5f-a474-9e8ea0ce4926").Environment(Environment.Sandbox).HttpClientFactory(New DefaultHttpClientFactory()).Build()

        Dim requestRRR As HostedPaymentRequest = New HostedPaymentRequest() With {
    .Amount = 10,
    .Currency = Currency.GBP,
    .PaymentType = PaymentType.Regular,
    .BillingDescriptor = New BillingDescriptor() With {
        .Name = "Name",
        .City = "City"
    },
    .Reference = "reference1",
    .Description = "Payment for Gold Necklace",
    .Customer = New CustomerRequest() With {
        .Email = "deepak.kumar@truetraveller.com",
        .Name = "FirstName LastName"
    },
    .Billing = New BillingInformation() With {
        .Address = New Address() With {
            .AddressLine1 = "Checkout.com",
            .AddressLine2 = "90 Tottenham Court Road",
            .City = "London",
            .State = "London",
            .Zip = "W1T 4TJ",
            .Country = CountryCode.GB
        },
        .Phone = New Phone() With {
            .Number = "4155552671",
            .CountryCode = "1"
        }
    },
    .SuccessUrl = "https://example.com/payments/success",
    .CancelUrl = "https://example.com/payments/cancel",
    .FailureUrl = "https://example.com/payments/failure",
    .Metadata = New Dictionary(Of String, Object)(),
    .Locale = "en-GB",
    .ThreeDs = New ThreeDsRequest() With {
        .Enabled = False,
        .AttemptN3D = False
    }
}

        Try
            Dim resp As HostedPaymentResponse = api.HostedPaymentsClient().Create(requestRRR).Result

        Catch ex As CheckoutApiException
            Dim requestId As String = ex.RequestId
            Dim statusCode = ex.HttpStatusCode
            Dim errorDetails As IDictionary(Of String, Object) = ex.ErrorDetails
        Catch exceptionMessage As CheckoutArgumentException
        Catch exceptionM As CheckoutAuthorizationException
        End Try
    End Sub

### Expected behavior

It should get the response. But no response it got struck in line: 
Dim resp As HostedPaymentResponse = api.HostedPaymentsClient().Create(requestRRR).Result .. Browser keep on rotating and no response.

### Current behavior

 it got struck in line: 
Dim resp As HostedPaymentResponse = api.HostedPaymentsClient().Create(requestRRR).Result .. Browser keep on rotating and no response and not hitted back on this line.

### Steps to reproduce

Run the code which I have mentioned on page load and it struck at line which I have mentioned.

### Possible solution

Don't Know

- [ ] I may be able to implement this bug fix
- [ ] Don't Know

**Comment by rsaestrela** [comment]
@timriley1234 Thanks for creating this issue. Please remove your Checkout credentials from the code samples. Closing this issue to avoid more exposure.

We will try to reproduce this issue and we'll get back to you.
