### ISSUE TITLE
Debugger is not hitting on hostage page payment request.

### ISSUE THREAD

**Issue by deepaknsp11** [checkout/checkout-sdk-net#169]
Debugger is not hitting on hostage page payment request.
 Dim response As HostedPaymentResponse = api.HostedPaymentsClient().Create(request).Result  -- It is struck on this line and not return or not going in error or catch exception.

### Environment

* Checkout SDK version: 3.5.1
* Platform and version: Visual Studio 19
* Operating System and version: Windows 10

### Description

Debugger is not hitting on hostage page payment request on the below line:
 Dim response As HostedPaymentResponse = api.HostedPaymentsClient().Create(request).Result  -- It is struck on this line and not return or not going in error or catch exception.

Code Reference:
Dim api As ICheckoutApi = CheckoutSdk.DefaultSdk().StaticKeys().PublicKey("pk_test").SecretKey("sk_test").Environment(0).HttpClientFactory(New DefaultHttpClientFactory()).Build()
        Dim request As HostedPaymentRequest = New HostedPaymentRequest() With {
        .Amount = 10,
        .Currency = Currency.GBP,
        .PaymentType = PaymentType.Regular,
        .PaymentIp = "192.168.0.1",
        .BillingDescriptor = New BillingDescriptor() With {
            .Name = "Name",
            .City = "City"
        },
        .Reference = "reference",
        .Description = "Payment for Gold Necklace",
        .Customer = New CustomerRequest() With {
            .Email = "email@docs.checkout.com",
            .Name = "FirstName LastName"
        },
        .Shipping = New ShippingDetails() With {
            .Address = New Address() With {
                .AddressLine1 = "Checkout.com",
                .AddressLine2 = "90 Tottenham Court Road",
                .City = "London",
                .State = "London",
                .Zip = "W1T 4TJ",
                .Country = CountryCode.GB
            },
            .Phone = New Phone() With {
                .Number = "4155552671",
                .CountryCode = "1"
            }
        },
        .Billing = New BillingInformation() With {
            .Address = New Address() With {
                .AddressLine1 = "Checkout.com",
                .AddressLine2 = "90 Tottenham Court Road",
                .City = "London",
                .State = "London",
                .Zip = "W1T 4TJ",
                .Country = CountryCode.GB
            },
            .Phone = New Phone() With {
                .Number = "4155552671",
                .CountryCode = "1"
            }
        },
        .Recipient = New PaymentRecipient() With {
            .DateOfBirth = "1985-05-15",
            .AccountNumber = "5555554444",
            .Zip = "WIT",
            .FirstName = "FirstName",
            .LastName = "LastName",
            .Country = CountryCode.GB
        },
        .Processing = New ProcessingSettings() With {
            .Aft = True
        },
        .Products = New List(Of Product)() From {
            New Product() With {
                .Name = "Gold Necklace",
                .Quantity = 1,
                .Price = 1000
            }
        },
        .Risk = New RiskRequest() With {
            .Enabled = False
        },
        .SuccessUrl = "https://example.com/payments/success",
        .CancelUrl = "https://example.com/payments/cancel",
        .FailureUrl = "https://example.com/payments/failure",
        .Metadata = New Dictionary(Of String, Object)(),
        .Locale = "en-GB",
        .ThreeDs = New ThreeDsRequest() With {
            .Enabled = False,
            .AttemptN3D = False
        },
        .Capture = True,
        .CaptureOn = New DateTime()
    }

        Try
            Dim response As HostedPaymentResponse = api.HostedPaymentsClient().Create(request).Result
            HttpContext.Current.Response.Redirect(response.Links("redirect").Href)
            Console.WriteLine("- Approved:" & response.Reference)
            Console.WriteLine(response.Links("redirect").Href)
        Catch exx As CheckoutApiException
            Dim requestId As String = exx.RequestId
            Dim statusCode = exx.HttpStatusCode
            Dim errorDetails As IDictionary(Of String, Object) = exx.ErrorDetails
            'Console.WriteLine("Error 1:" & exx)
        Catch ex1 As CheckoutArgumentException
            'Console.WriteLine("Error 2:" & ex1)
        Catch ex2 As CheckoutAuthorizationException
            'Console.WriteLine("Error 3:" & ex2)
        End Try

### Expected behavior

It should return response with href to redirect to hosted payment page.

### Current behavior

Debugger is not hitting on hostage page payment request on the below line:
 Dim response As HostedPaymentResponse = api.HostedPaymentsClient().Create(request).Result  -- It is struck on this line and not return or not going in error or catch exception.

### Steps to reproduce

Run the code on with test public key and private key on button click or page load. It will struck on the line which I have mentioned in description.

### Possible solution

Don't know.
- [ ] I may be able to implement this bug fix
Don't know

**Comment by oferns** [comment]
Your problem is not with the SDK but with using .Result on a task. You should either await it, or use Task.Wait(). 

This might help
https://stackoverflow.com/questions/47284290/when-is-the-best-place-to-use-task-result-instead-of-awaiting-task

If you want to catch the exception that is being thrown here then either Catch Exception or Catch AggregateException

**Comment by oferns** [comment]
Hi,
if you look at this 
https://stackoverflow.com/questions/53529061/whats-the-right-way-to-use-httpclient-synchronously/53529122

the prinicple is the same (this is C'# but it should be trivial to turn to VB.NET)

```
var task = Task.Run(() => myHttpClient.GetAsync(someUrl)); 
task.Wait();
var response = task.Result;
```

Ideally you would await it in asynchronous manner because there is no "one-size fits all" way to run async tasks synchronously in .NET without risking deadlocks. We should close this  ticket though because it is nothing to do with this repo or the SDK

Thanks,
Ollie

**Comment by deepaknsp11** [comment]
@oferns ,

Thank you support. Got your point. Now it worked when I had used task wait. I am closing this ticket.
