### ISSUE TITLE
Add ChallengeIndicator to ThreeDsRequest for Checkout SDK version 2.x.x

### ISSUE THREAD

**Issue by serenata-genadiy** [checkout/checkout-sdk-net#180]
Please add ChallengeIndicator to ThreeDsRequest for Checkout SDK version 2.x.x

### Environment
* Checkout SDK version: 2.5.0

### Description
The ChallengeIndicator was added to ThreeDsRequest in version v 3.7.2, but Checkout SDK v.3+ has breaking changes. Is it possible to have the ChallengeIndicator added to ThreeDsRequest as v. 2. 6.0?

## Proposed Solution
Create a new Checkout SDK version from 2.5.0 which includes the changes from the following pull request:
https://github.com/checkout/checkout-sdk-net/commit/25572e266284e17f596221c55e7cb4d0361e1f0d

**Comment by rsaestrela** [comment]
Hi @serenata-genadiy. Thanks for creating this issue. We're going to evaluate that change and we will let you know as soon as possible.

**Comment by rsaestrela** [comment]
Hi @serenata-genadiy. We are working on your request. I'll notify you when the new version is released.

**Comment by rsaestrela** [comment]
Hi @serenata-genadiy. A legacy build from 2.5.0 - [2.5.1 was just published](https://www.nuget.org/packages/CheckoutSDK/2.5.1) containing the change you requested. Please let us know if this works for you. Please keep in mind that we will not support modern features & compatibility patches on these kind of releases  as we kindly ask you to migrate to the latest 3.x.x as soon as possible. Please let us know if you need support with the migration, we're here to help :)

**Comment by serenata-genadiy** [comment]
Hi @rsaestrela,  
I can confirm 2.5.1 works fine for me. Thank you.
