### ISSUE TITLE
URGENT: ApplePay tokenization not working on SDK 2.5.1

### ISSUE THREAD

**Issue by mohamad-rmeity-cko** [checkout/checkout-sdk-net#188]
Hello,

We previously requested a new release for SDK 2.5 where the token validation would be altered to take the new API keys. 
That resolved all the issues with the keys, however at the moment the merchant is facing issues with the Apple Pay tokenization. 
This is due to the fact that the token type is being sent as 'ApplePay' and not 'applepay'. On MBC, it did not matter if the token type is 'ApplePay' or 'applepay'. However, on NAS, it must be 'applepay' at all times.

Can you please urgently assist us with this? We're aware that currently this is not following best practice, however we currently have no other option other than following this. So all we need to do is change the WalletType from 'ApplePay' to 'applepay' instead.

Thank you

**Comment by rsaestrela** [comment]
Released [2.5.1](https://www.nuget.org/packages/CheckoutSDK/2.5.2).
