### ISSUE TITLE
Migration guide from 2.5 to 3.7

### ISSUE THREAD

**Issue by knopa** [checkout/checkout-sdk-net#191]
Dear,

Is there any migration guide for 2.5 to 3.7?
Any flow changes?

**Comment by rsaestrela** [comment]
Hi @knopa. Sorry for the delay. Answering to your question - unfortunately we don't have a migration guide. The SDK instantiation is very different (explained in the README.md), however the SDK usage semantics are pretty similar. The key is to identify and use the SDK in accordance with the API keys you have - this will select the right `ICheckoutApi` and from there it should be easy to refactor your current implementation.

All the [code samples](https://api-reference.checkout.com/preview/crusoe/) are up to date so you should be able to find some examples on how to use the different operations. Feel free to open new issues to get support on how to integrate the newest versions. We'd be happy to help you!

**Comment by knopa** [comment]
@rsaestrela Thanks for reply.

Is there any information for deadlines when 2.5 will be still active?

**Comment by rsaestrela** [comment]
Legacy builds 2.5.X will be always available but they're based on an outdated codebase. It's not actively updated and it has major incompatibilities with Four API (in case you have Four keys, this is a hard no-go). 

For this reason we delivered v3 recently (latest, 3.7.4) that contains not only a bunch of new features, but compatibility with different key types and OAuth. We have been providing updates on a weekly/bi-weekly basis. This should be the way to go in the long run as we do not plan to bring major breaking changes in the next versions. Please let us know if we can support you transitioning to the latest version.

**Comment by knopa** [comment]
I mean from API side what LTS end term. Just to plan how much time i have for updating it?

**Comment by knopa** [comment]
Am I right it will not work with platform migration?
