### ISSUE TITLE
Named HttpClient

### ISSUE THREAD

**Issue by sipsorcery** [checkout/checkout-sdk-net#230]
Is there any reason a named HttpClient is not being used in the [ApiClient](https://github.com/checkout/checkout-sdk-net/blob/9c03b013d9c2775f6c123d8cd5e5753c8c830dfd/src/CheckoutSdk/ApiClient.cs#L25) so that the [ASP.NET Core IHttpClientFactory DI](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-5.0#named-clients-1) can be taken advantage of?

If it was:

````
public ApiClient(IHttpClientFactory httpClientFactory, Uri baseUri)
{
    CheckoutUtils.ValidateParams("httpClientFactory", httpClientFactory, "baseUri", baseUri);
    var httpClient = httpClientFactory.CreateClient("Checkout");
    httpClient.BaseAddress = baseUri;
    _httpClient = httpClient;
}
````

In `Statup.cs` I could:

````
services.AddHttpClient("Checkout", httpClient =>
{
      httpClient.Timeout = TimeSpan.FromSeconds(httpClientTimeoutSeconds);
     // etc.
})
````

It seems a bit of overkill to need to create a new class:

````
private class TestingClientFactory : IHttpClientFactory
{
    public HttpClient CreateClient()
    {
        var httpClient = new HttpClient(new CustomMessageHandler());
        httpClient.Timeout = TimeSpan.FromSeconds(2);
        return httpClient;
    }
}
````

**Comment by Armando-Ibarra** [comment]
Hi @sipsorcery 
We basically tried to support the most posible to some users who does not use DI in their systems, so we provide the most friendly way to include his own versions of HttpClients.

This is a good idea for a feature request, however this could take some time to be develop due the amount of features in other SDK's.

But if you want to sheppard this request feel free to open a PR.
