### ISSUE TITLE
Confusion on validity of public/secret keys using Default/Previous for sandbox env

### ISSUE THREAD

**Issue by Antaris** [checkout/checkout-sdk-net#250]
I'm looking to upgrade from a legacy v1.2.0 integration using the newer v4 integration. I'm having trouble instantiating the API client in line with your example:

<img width="438" alt="image" src="https://user-images.githubusercontent.com/255906/191372366-3f7a944b-43e5-4bdd-87f2-16c3ed7bdc29.png">

> Note: sandbox keys have a sbox_ or test_ identifier, for Default and Previous accounts respectively.

You suggest here, that 'Default' uses the shorter public/secret key formats, and not the uuid/guid based formats of 'Previous'. 

However, this seems to conflict with the implementation details in `PreviousStaticKeysSdkCredentials` (previous) and `StaticKeysSdkCredentials` (default):

- Only `PreviousStaticKeysSdkCredentials` supports the `test_` token in the key
- Only `StaticKeysSdkCredentials` supports the `sbox_` token in the key.

I however, have a shorter (default) format set of keys given to be by Checkout.com, which uses `test_` in the token, not the `sbox_` token.

Are the regex patterns around the wrong way for these two implementations?

**Comment by Armando-Ibarra** [comment]
Hey @Antaris can you double with your customer support that you receive the proper keys?

As far as I know the previous instance (ABC) belongs to keys with the following format
`sk_test_12345678-1234-1234-1234-1234567890AB`

And default instance (NAS) belongs to keys with format
`sk_sbox_eszrdxtfcygvuhbijnokmpoilkj`

**Comment by Armando-Ibarra** [comment]
Let us know if you have any other issue, or re open if the issue persist.
Thanks!
