### ISSUE TITLE
Support for new (beta) reporting API

### ISSUE THREAD

**Issue by IanKemp** [checkout/checkout-sdk-net#257]
There does not appear to be any support for the beta [reporting API](https://api-reference.checkout.com/#tag/Reports) in this SDK yet. Is this something that is one the team's roadmap and if so, any rough timeline on release? Or will such capabilities only be added once that API is no longer beta?

**Comment by Armando-Ibarra** [comment]
Hi @IanKemp 
Yes we are going to support Reporting API, but is tracked as low priority right now, we could bring a first version without [redirect](https://api-reference.checkout.com/#operation/getReportFile) endpoint, HttpClient has some issues with redirect that we need to consider, but we are focused on other high priority stuff.

**Comment by IanKemp** [comment]
> Hi @IanKemp Yes we are going to support Reporting API, but is tracked as low priority right now, we could bring a first version without [redirect](https://api-reference.checkout.com/#operation/getReportFile) endpoint, HttpClient has some issues with redirect that we need to consider, but we are focused on other high priority stuff.

Yes, I'm well aware of the issue with the HTTPS-to-HTTP redirection and the fact that HttpClient doesn't support this for security reasons - because I had to write a workaround for this API behaviour just yesterday. Is there any way to avoid this being necessary, e.g. by transparently proxying the HTTP response from AWS so it's served up via the HTTPS GetReport endpoint?

**Comment by IanKemp** [comment]
Another feature request for this API: for the [/reports endpoint](https://api-reference.checkout.com/#operation/getReports), add a query (filter) parameter to filter by report type.

For example, if I'm only interested in [financial actions by payout ID](https://www.checkout.com/docs/reporting/reconciliation-reports/financial-actions-reports#Financial_actions_by_payout_ID) reports for a certain day, I'd like to be able to send the following request:

GET /reports?created_after=YYYY-MM-DD&report_type=FinancialActionsByPayoutId

**Comment by Armando-Ibarra** [comment]
Hey @IanKemp  we just released #261  a new version which includes parts of Reports API, redirect is still not supported for now, but we will add that feature later, let us know if that works for you.

Regarding your feature request, you might want to reach out your Client Support contact, because the API development belongs to another team.

**Comment by IanKemp** [comment]
@Armando-Ibarra Thanks for the new version - it's a start at least!

Regarding the report redirect issue, after experimenting I discovered that the AWS bucket storing the reports does seem to be enabled for HTTPS access - i.e. if I take the HTTP URL given to me by the API and change it to use HTTPS, the report file downloads successfully. This would suggest to me that the issue here is a simple one of configuration and if the redirect was changed to HTTPS there would no longer be a problem - hopefully that's helpful to you.

**Comment by armando-ibarra-cko** [comment]
All Report modules are supported now, please let us know any issue.

**Comment by IanKemp** [comment]
@armando-ibarra-cko is this as of the latest released version 4.0.12?

**Comment by armando-ibarra-cko** [comment]
Hey @IanKemp  sorry for the delay, yes it was released on #303

**Comment by armando-ibarra-cko** [comment]
Oh I see, it was not added into the changelog but was merged in #298
