### ISSUE TITLE
DTO classes for specific webhook events

### ISSUE THREAD

**Issue by roberthardy** [checkout/checkout-sdk-net#265]
### Environment

* Checkout SDK version: 4.0.6
* Platform and version: .NET 6.0
* Operating System and version:

### Description
Is it possible for the SDK to include classes/records to represent each specific webhook event? This would make it easier to consume webhook events. Currently I have to define these types myself. E.g.
```csharp
public sealed record PaymentApprovedEvent(
	string Id,
	string Type,
	DateTimeOffset CreatedOn,
	Data Data,
	Links Links
);

public sealed record _3ds(
	string Version,
	//...
	string Xid
);

public sealed record BillingAddress(
	string AddressLine1,
	//...
);

public sealed record Customer(
	string Id,
	//...
);

// etc...

```
Ideally, the SDK would also include some helper classes for doing the deserialization and/or model binding.

## Proposed Solution

Use some kind of code gen.

- [ ] I may be able to implement this feature

**Comment by Armando-Ibarra** [comment]
Hi @roberthardy Thank you opening this issue.

By webhooks, you mean this [operation](https://api-reference.checkout.com/previous/#operation/retrieveWebhook)?

**Comment by roberthardy** [comment]
Hi @Armando-Ibarra . Checkout sends requests to a webhook receiver that we have implemented using ASP.NET Core. These requests contain a JSON payload with information about the event (see [this example](https://www.checkout.com/docs/workflows/webhook-event-types/payment_approved)). On receiving this JSON payload we deserialize it into a statically typed object instance in order to process the event. E.g.
```csharp
public sealed record PaymentApprovedEvent(string Id, DateTimeOffset CreatedOn, Data Data);
// ...
public void WebhookReceiver(string jsonPayloadReceivedFromCheckout)
{
    PaymentApprovedEvent paymentApprovedEvent = JsonSerializer.Deserialize<PaymentApprovedEvent>(jsonPayloadReceivedFromCheckout);
    // Do something with paymentApprovedEvent...
}
```
As you can see, we have defined the `PaymentApprovedEvent` type to represent the `payment_approved` webhook event. We wrote this type definition based on the [available documentation](https://www.checkout.com/docs/workflows/webhook-event-types/payment_approved) that we're aware of. I'm guessing that most .NET projects that integrate with Checkout.com would have similar type definitions. It would reduce a lot of development effort if a library of type definitions to represent all of the [webhook event types](https://www.checkout.com/docs/workflows/webhook-event-types) was made available either in the Checkout .NET SDK package or a separate package.

**Comment by Armando-Ibarra** [comment]
I see.

So the thing is, our concern is that we need to map all the Event types, the examples provided on Docs page shows only a few, however if you see the definition on [API reference](https://api-reference.checkout.com/#tag/Workflows/paths/~1workflows~1events~1{eventId}/get) we don't have all the data that and event could have, that's the reason why you don't see a custom serialization, it is hard to tell if the parsing that we are doing to be correct

**Comment by roberthardy** [comment]
OK so what you're saying is, when Checkout.com sends an event notification request to our webhook receiver URL, that request could contain anything? E.g. a `payment_approved` event might have data of the same shape as [the example](https://www.checkout.com/docs/workflows/webhook-event-types/payment_approved) for some cases but for other cases the `payment_approved` event data could be significantly different?

**Comment by Armando-Ibarra** [comment]
No, we don't have all the mappings that an event could have, because we're receiving any event not only payment_approved. You might want probably create an issue here https://github.com/checkout/checkout-api-reference which is where docs team manage the API reference, once that we have all the mappings in API reference, we could create the proper mappings on SDK's

**Comment by roberthardy** [comment]
Thanks @Armando-Ibarra. I'll consider raising an issue in the checkout-api-reference project.
