### ISSUE TITLE
Feature request: make AddCheckoutSdk() an extension method 

### ISSUE THREAD

**Issue by IanKemp** [checkout/checkout-sdk-net#273]
### Description

* Make `CheckoutSDK.Extensions.Configuration.CheckoutServiceCollection.AddCheckoutSdk()` an extension method so it can be called as `IServiceCollection.AddCheckoutSdk(IConfiguration, ILoggerFactory, IHttpClientFactory)`.

## Proposed Solution

Add `this` modifier to first argument of the method.

- [x] I may be able to implement this feature

**Comment by Armando-Ibarra** [comment]
Released on #290, let us know if you face any issue
