### ISSUE TITLE
Feature request: allow configuration section name to be specified in CheckoutSDK.Extensions

### ISSUE THREAD

**Issue by IanKemp** [checkout/checkout-sdk-net#274]
### Description

Currently the `CheckoutSDK.Extensions.Configuration.CheckoutConfigurationHelper.GetCheckoutOptions(IConfiguration)` method attempts to bind to a section named "Checkout" in the provided `IConfiguration`. In our case we already have a section called "Checkout" in our configuration file, but with different keys and values specific to how our code that talks to CKO operates.

* We do not want to rename this section as it is currently referenced across our estate.
* We do not want to put the Checkout SDK variable values into this section, as we are concerned about clashes with our own variables (e.g. if CKO adds a property on `CheckoutOptions` that has the same name as one of our config keys, the binder will use that property, which could have unintended side effects)

Ideally we'd like to be able to define a subsection within our current "Checkout" section, containing only the SDK-specific values, and tell CheckoutSDK.Extensions to use that, e.g.:

```
"Checkout": {
   "Sdk": {
        // CKO API config e.g. SecretKey, Environment, ...
    },
    // our config
}
```

But because of the hardcoded section name, we cannot do this. (Of course, if we don't use CheckoutSDK.Extensions and bind manually this is not a problem, which is what we're doing currently.)

## Proposed Solution

* Add an overload of `CheckoutSDK.Extensions.Configuration.CheckoutConfigurationHelper.GetCheckoutOptions()`:
```
public static CheckoutOptions GetCheckoutOptions(this IConfigurationSection configurationSection)
    => configurationSection.Get<CheckoutOptions>();
```
* Make current `GetCheckoutOptions()` call new overload to preserve current behaviour:
```
public static CheckoutOptions GetCheckoutOptions(this IConfiguration configuration)
    => GetCheckoutOptions(configuration.GetSection("Checkout"));
```
* Add an overload of `CheckoutSDK.Extensions.Configuration.CheckoutServiceCollection.AddCheckoutSdk()` that calls the new `GetCheckoutOptions(IConfigurationSection)`:
```
public static IServiceCollection AddCheckoutSdk(
            this IServiceCollection serviceCollection,
            IConfigurationSection configurationSection,
            ILoggerFactory loggerFactory = null,
            IHttpClientFactory httpClientFactory = null)
```

Then clients can call:

```
IServiceCollection.AddCheckoutSdk(configuration.GetSection("Whatever").GetSection("NestedSection").GetSection("YouWant"), ...);
```

**Problem:** because `IConfigurationSection` implements `IConfiguration`, this may cause overload resolution problems. The above code has not yet been trested.

- [x] I may be able to implement this feature

**Comment by Armando-Ibarra** [comment]
Released on #290, let us know if you face any issue
