### ISSUE TITLE
Error when call Get Payment Link details api C#

### ISSUE THREAD

**Issue by musab-alrmmah** [checkout/checkout-sdk-net#283]
when call Get Payment Link details. It Exits from the service and shows this error

"{"Message":"An error has occurred.","ExceptionMessage":"The type initializer for 'Checkout.LogProvider' threw an exception.","ExceptionType":"System.TypeInitializationException","StackTrace":"   at Checkout.LogProvider.GetLogger(Type clazz)\r\n   at Checkout.ApiClient..ctor(IHttpClientFactory httpClientFactory, Uri baseUri)\r\n   at Checkout.CheckoutApi.BaseApiClient(CheckoutConfiguration configuration)\r\n   at Checkout.CheckoutApi..ctor(CheckoutConfiguration configuration)\r\n   at Checkout.CheckoutSdkBuilder.CheckoutStaticKeysSdkBuilder.Build()\r\n   at Controller.<GetLinkeDetailes>d__10.MoveNext() in End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__1`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()","InnerException":{"Message":"An error has occurred.","ExceptionMessage":"Could not load file or assembly 'System.ValueTuple, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.","ExceptionType":"System.IO.FileNotFoundException","StackTrace":"   at Microsoft.Extensions.Logging.LoggerFactory.RefreshFilters(LoggerFilterOptions filterOptions)\r\n   at Microsoft.Extensions.Logging.LoggerFactory..ctor(IEnumerable`1 providers, IOptionsMonitor`1 filterOption)\r\n   at Microsoft.Extensions.Logging.LoggerFactory..ctor(IEnumerable`1 providers)\r\n   at Microsoft.Extensions.Logging.LoggerFactory..ctor()\r\n   at Checkout.LogProvider..cctor()"}}"

**Comment by Armando-Ibarra** [comment]
Hi @musab-alrmmah 

The Stack Trace doesn't point to any of the Payments Client code.

Did you test that your implementation works for any other operation? This seems an error of dependencies on your logger.

**Comment by Armando-Ibarra** [comment]
@musab-alrmmah 
Do you have any of the `Microsoft.Extensions.Logging` dependencies?
And also which Target Framework are you using?

**Comment by Armando-Ibarra** [comment]
@musab-alrmmah Please check if you have any `System.ValueTuple` dependency installed.

It seems that any of your dependencies is causing a conflict between the  .Net Framework inner dependency.

(Not SDK related)

**Comment by Armando-Ibarra** [comment]
Seems that ValueTuple is the root cause.
You need either upgrade or downgrade the version of that dependency, [see](https://stackoverflow.com/questions/42867434/could-not-load-file-or-assembly-system-valuetuple)

I think internally Microsoft.Extensions.Logging.LoggerFactory is using that `ValueTuple`, somehow it has some conflicts with your own dependency.

**Comment by musab-alrmmah** [comment]
@Armando-Ibarra 

I'm using Checkout SDK and I downgrade the version and yet the service didn't work for me, what's the solution?

**Comment by Armando-Ibarra** [comment]
@musab-alrmmah I don't know why you need to use a custom `System.ValueTuple` dependency, the root cause is clearly a mismatch of dependency, since this is an error that is not related to the SDK I recommend investigating some approaches.

**Comment by Armando-Ibarra** [comment]
Will close this one. Please let us know if you face any issue regarding with this SDK.
