### ISSUE TITLE
Error when call Get Payment Link details api jQuery

### ISSUE THREAD

**Issue by musab-alrmmah** [checkout/checkout-sdk-net#284]
when call Get Payment Link details. It Exits from the service and shows this error

Access to XMLHttpRequest at 'https://api.sandbox.checkout.com/payment-links/ID' from origin 'https://SUBDOMAIN.MYDOMAIN.COM:XXXX' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

this my code 

var settings = {
  "url": "https://api.sandbox.checkout.com/payment-links/ID",
  "method": "GET",
  "timeout": 0,
  "headers": {
    "Authorization": secrit_key
  },
};

$.ajax(settings).done(function (response) {
  console.log(response);
});

**Comment by armandojaleo** [comment]
Dear @musab-alrmmah, to make calls to the Checkout API you must use the SDK of the language you need, we do not support code that does not use the SDK, sorry.
We recommend that you debug your call using a client like Postman.

**Comment by Armando-Ibarra** [comment]
Will close this one. Please let us know if you face any issue regarding with this SDK.
