### ISSUE TITLE
Error when building project with Xamarin Android linking SDK Assemblies in Release mode

### ISSUE THREAD

**Issue by Ayoub-Abuhamdeh** [checkout/checkout-sdk-net#315]
Environment

Checkout SDK version: 4.0.14
Platform and version: Xamarin.Forms
Operating System and Version: Xamarin.Android

Description
- I encountered an error when attempting to build the project with only the Android linking SDK Assemblies included and in Release mode.

Expected behavior
- The project should build successfully without any errors.

Current behavior
- During the build process, I received the following error:

`Severity	Code	Description	Project	File	Line	Suppression State
Error		Mono.Linker.MarkException: Error processing method: 'System.String Microsoft.Net.Http.Headers.DateTimeFormatter::ToRfc1123String(System.DateTimeOffset,System.Boolean)' in assembly: 'Microsoft.Net.Http.Headers.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve Microsoft.Extensions.Primitives.InplaceStringBuilder
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedType(TypeReference reference)
   at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference)
   at MonoDroid.Tuner.MonoDroidMarkStep.MarkType(TypeReference reference)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.RunTask()
   at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:line 17
`
. Steps to reproduce

- Include only the Android linking SDK Assemblies in the project.
- Build the project in Release mode.

. Possible solution
- I'm not certain about the exact cause of this issue, but it appears to be related to the unresolved type Microsoft.Extensions.Primitives.InplaceStringBuilder. It might be helpful to check if there are any missing dependencies or if there are conflicting versions of libraries in the project.

. Additional information

- Version of checkout-sdk-net: [4.0.14 and all lower versions]
- Version of Android SDK: [Android 13]
- Version of Xamarin: [5.0.0.2337]
- Operating System: [Windows 10]
Please let me know if there's any further information needed.

**Comment by armando-ibarra-cko** [comment]
Hello @Ayoub-Abuhamdeh 

With the given information, it is hard to tell why this is an issue with the SDK, since either the log provided and the libraries do not match with anything related to this SDK. You might need to provide additional information or review your dependencies, since we are using only the default systems dependencies. You may need to check why `Microsoft.Net.Http.Headers.DateTimeFormatter` is causing problems.

**Comment by Ayoub-Abuhamdeh** [comment]
Hello @armando-ibarra-cko,

Thank you for your prompt response. I understand your concerns regarding the provided information and the libraries involved. I apologize for any confusion caused.

I want to clarify that I have provided all the relevant information available, including the log and error messages. The issue occurs specifically when the Linking behavior is set to "SDK and Assemblies only" in Release mode. In any other configuration, the build does not fail.

Considering this, it appears that there might be an interaction between the SDK and the linking process. I will further investigate the dependencies and specifically focus on the Microsoft.Net.Http.Headers.DateTimeFormatter library to determine why it is causing problems.

If there are any specific suggestions or guidance you can provide to assist with this investigation, it would be greatly appreciated. Please let me know if there are any additional details or logs that would be helpful in resolving this issue.

Please find the attached image..
![image](https://github.com/checkout/checkout-sdk-net/assets/49373951/7d250acc-3ab4-4ef2-b198-cc8256536fd1)

Thank you for your cooperation.

**Comment by SDwaik** [comment]
I have the same issue when  Linking the App "SDK and Assemblies only"

without linking 
![image](https://github.com/checkout/checkout-sdk-net/assets/11909779/e2f6fab7-bb02-4a74-b5ee-69e572c9a095)

with Linking 

![image](https://github.com/checkout/checkout-sdk-net/assets/11909779/f32b13c3-99e7-4ad1-85ae-bebf98d0aa9a)

**Comment by armando-ibarra-cko** [comment]
In our side, seems that this package may cause the issue 
I'm having a look if we can remove the dependency

  <PackageReference Include="Microsoft.AspNetCore.WebUtilities" Version="2.2.0" />

**Comment by armando-ibarra-cko** [comment]
PR #316

**Comment by Ayoub-Abuhamdeh** [comment]
Dear @armando-ibarra-cko ,

We were able to successfully build our project by setting the linker behavior to "SDK and assemblies only" in release mode.
We greatly appreciate the effort and dedication your team has shown throughout this process. 

Once again, thank you for your support. We are now closing the issue, and we look forward to continued collaboration in the future.

Best regards,
Ayoub
