### ISSUE TITLE
Newtonsoft.Json 13.0.3' is not compatible with 'CheckoutSDK 4.0.22

### ISSUE THREAD

**Issue by eplatforms-uk** [checkout/checkout-sdk-net#345]
'Newtonsoft.Json 13.0.3' is not compatible with 'CheckoutSDK 4.0.22 constraint: Newtonsoft.Json (>= 9.0.1 && <= 13.0.1)'.

**Comment by armando-rodriguez-cko** [comment]
Please @eplatforms-uk can you give us more details? Do you mean if you can't install this version? There is a new PR to change this: https://github.com/checkout/checkout-sdk-net/pull/344

**Comment by eplatforms-uk** [comment]
> Please @eplatforms-uk can you give us more details? Do you mean if you can't install this version? There is a new PR to change this: #344

Yes this is correct we can't install - we get that error

**Comment by eplatforms-uk** [comment]
> Please @eplatforms-uk can you give us more details? Do you mean if you can't install this version? There is a new PR to change this: #344

Yes this is correct we can't install - we get that error

**Comment by eplatforms-uk** [comment]
> Please @eplatforms-uk can you give us more details? Do you mean if you can't install this version? There is a new PR to change this: #344

Yes this is correct we can't install - we get that error

> Please @eplatforms-uk can you give us more details? Do you mean if you can't install this version? There is a new PR to change this: #344

**Comment by armando-rodriguez-cko** [comment]
A soon as possible, before Friday, we will launch a new release with this change.
