### ISSUE TITLE
The payment request misses the partial_authorization field

### ISSUE THREAD

**Issue by oleksii-i-iol** [checkout/checkout-sdk-net#397]
### Environment

* Checkout SDK version: 4.2.1
* Platform and version: .NET 8
* Operating System and version: Windows

### Description
Related to the documentation [here ](https://www.checkout.com/docs/payments/manage-payments/authorize-a-payment#Request_a_partial_authorization) there should be the ability to pay with **partial_authorization** flag.

### Expected behavior
Use the SDK with all necessary fields that are described in the documentation and API reference source.

### Current behavior
Some fields don't exist, the SDK can't be fully used with all features

### Possible solution
Add all necessary fields to SDK

- [ ] I may be able to implement this bug fix

**Comment by armando-rodriguez-cko** [comment]
Thank you @oleksii-i-iol! We will update it next release.

**Comment by armando-rodriguez-cko** [comment]
New release launched with the changes: https://github.com/checkout/checkout-sdk-net/pull/404
