### ISSUE TITLE
Phone property missing in TokenSource

### ISSUE THREAD

**Issue by riaz-bordie-cko** [checkout/checkout-sdk-net#42]
https://github.com/checkout/checkout-sdk-net/blob/master/src/CheckoutSdk/Payments/TokenSource.cs

seems to be missing `Phone`

**Comment by rsaestrela** [comment]
Hi @riaz-bordie-cko. Thank you for opening this issue. We are releasing a new [major version](https://github.com/checkout/checkout-sdk-net/pull/105) in the next days that will include the field `Phone` at `RequestTokenSource` level. If you have any further questions, please reopen this issue or create a new one.
