### ISSUE TITLE
SchemeId missing in PaymentProcessed

### ISSUE THREAD

**Issue by riaz-bordie-cko** [checkout/checkout-sdk-net#43]
https://github.com/checkout/checkout-sdk-net/blob/master/src/CheckoutSdk/Payments/PaymentProcessed.cs

Seeing `scheme_id` returned from the API - it's also in the docs @ Request A Payment

Missing in the model

**Comment by philippe-leonhardt-cko** [comment]
Merged into develop branch with #100 .
Merge into master pending for release.
