### ISSUE TITLE
CheckoutSDK vs Checkout.APIClient clarification

### ISSUE THREAD

**Issue by pollax** [checkout/checkout-sdk-net#58]
Hi,
What's the difference between CheckoutSDK and Checkout.APIClient other than CheckoutSDK being the "newer" one?

What APIs are supported/not supported in CheckoutSDK? For example, is anything related to recurring payments supported? Judging by the source I'd say no, so is support for that planned?

The documentation should contain a section for comparison between new/old versions I think.

**Comment by rsaestrela** [comment]
Hi @pollax . Thank you for opening this issue. We are releasing a new [major version](https://github.com/checkout/checkout-sdk-net/pull/105) in the next days that will include a new SDK instantiation layer. Creating and using the SDK will be much easier as your won't have to worry too much about these differences. Instructions how to use it will be documented in README.md. If you have any further questions, feel free to reopen this issue or to create a new one.
