### ISSUE TITLE
Acceptable Amount 

### ISSUE THREAD

**Issue by MuhammadSayed** [checkout/checkout-sdk-net#70]
Hi, 

I want to create a payment request with a **decimal number such as 12.5 $** but the API and SDK  accept only **Integer.** in amount parameter 

how can i create payment request with amount like this 12.5 $ , there is a way to send decimal amount

thanks

**Comment by david-fiaty-cko** [comment]
@MuhammadSayed, the SDK accepts only integers but you can send decimal amounts.
You just have to multiply the amount by 100 before sending it to the gateway.

If you want to create a payment request for an amount of 12.54 $ for example, the value to send to the gateway is 12.54*100 = 1254.

In general, always multiply the amount by 100 before sending it. If you want to charge 12.00 $, send 1200 to the gateway. If you send 12 to the gateway, it will be understood as 0.12.

**Comment by MuhammadSayed** [comment]
thanks David Fiaty for your support

**Comment by david-fiaty-cko** [comment]
@MuhammadSayed, you're very welcome. Please follow the link below for more information in the documentation: https://docs.checkout.com/docs/calculating-the-value
